### ISSUE TITLE
HTTP 400: Bad Request (Missing argument barcode)

### ISSUE THREAD

**Issue by antgonza** [biocore/american-gut-web#185]
If you click on the links generated on the "Your samples are ready" banner, you get this error:

```
[E 141003 12:08:19 base_handlers:21] (<class 'tornado.web.MissingArgumentError'>, MissingArgumentError(), <traceback object at 0x21f8f80>)
    Traceback (most recent call last):
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1332, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 2607, in wrapper
        return method(self, *args, **kwargs)
      File "/home/qiita/american_gut/amgut/handlers/sample_overview.py", line 59, in get
        self._sample_overview_renderer()
      File "/home/qiita/american_gut/amgut/handlers/sample_overview.py", line 19, in _sample_overview_renderer
        barcode = self.get_argument('barcode')
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 379, in get_argument
        return self._get_argument(name, default, self.request.arguments, strip)
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 448, in _get_argument
        raise MissingArgumentError(name)
    MissingArgumentError: HTTP 400: Bad Request (Missing argument barcode)
[W 141003 12:08:19 web:1811] 400 GET /authed/sample_overview/ (127.0.0.1) 6.12ms
```

**Comment by takishi** [comment]
Hi ElDeveloper, 
so.. ? 

best regards

**Comment by ElDeveloper** [comment]
What is this in reference to?

**Comment by takishi** [comment]
Hi @ElDeveloper 
still i have the problem!

URL: http://196.178.20.60:8801/api/v2/push 
Reponse:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1390, in _execute
    result = self.prepare()
  File "/root/airnotifier/api/__init__.py", line 82, in prepare
    self.appname = filter_alphabetanum(self.get_argument('appname'))
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 385, in get_argument
    return self._get_argument(name, default, self.request.arguments, strip)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 462, in _get_argument
    raise MissingArgumentError(name)
MissingArgumentError: HTTP 400: Bad Request (Missing argument appname)

can you help me to solve it

best regards.
samuel.

**Comment by ElDeveloper** [comment]
If you are having trouble accessing the AG website, please refer to the
help line: info@americangut.org
