### ISSUE TITLE
URGENT: new exceptions on production

### ISSUE THREAD

**Issue by wasade** [biocore/american-gut-web#344]
There are at least two issues below. The first one is the `__getitem__` issue with logging a sample. The second has to deal with sending an email when an exception happens. @beaugunderson, I think the recent PR that I prematurely merged is associated with the latter issue, can you comment when you have a moment?

```python
[E 141030 07:19:03 web:1407] Uncaught exception POST /authed/add_sample_human/ (127.0.0.1)
    HTTPServerRequest(protocol='http', host='microbio.me', method='POST', uri='/authed/add_sample_human/', version='HTTP/1.0', remote_ip='127.0.0.1', headers={'Origin': 'http://microbio.me', 'Content-Length': '114', 'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'X-Forwarded-For': '173.76.245.236', 'Host': 'microbio.me', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) AppleWebKit/600.1.25 (KHTML, like Gecko) Version/8.0 Safari/600.1.25', 'Dnt': '1', 'Connection': 'close', 'Referer': 'http://microbio.me/AmericanGut/authed/add_sample_animal/?participant_name=lexi', 'X-Real-Ip': '173.76.245.236', 'Cookie': '_ga=GA1.2.1784735214.1412891999; _gat=1; skid="2|1:0|10:1414675081|4:skid|16:ImF1YV92ZGdneSI=|59162460a8b824e959c29e10b6257537c06071c249c461966fc9ede92f0daa27"', 'Content-Type': 'application/x-www-form-urlencoded'})
    Traceback (most recent call last):
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1332, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 2607, in wrapper
        return method(self, *args, **kwargs)
      File "/home/qiita/american_gut/amgut/handlers/add_sample.py", line 42, in post
        notes)
      File "/home/qiita/american_gut/amgut/lib/data_access/ag_data_access.py", line 446, in logParticipantSample
        sql, (ag_login_id, participant_name))[0]
    TypeError: 'NoneType' object has no attribute '__getitem__'
[E 141030 07:19:03 base_handlers:25] (<type 'exceptions.TypeError'>, TypeError("'NoneType' object has no attribute '__getitem__'",), <traceback object at 0x18a5bd8>)
    Traceback (most recent call last):
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1332, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 2607, in wrapper
        return method(self, *args, **kwargs)
      File "/home/qiita/american_gut/amgut/handlers/add_sample.py", line 42, in post
        notes)
      File "/home/qiita/american_gut/amgut/lib/data_access/ag_data_access.py", line 446, in logParticipantSample
        sql, (ag_login_id, participant_name))[0]
    TypeError: 'NoneType' object has no attribute '__getitem__'
[E 141030 07:19:03 web:931] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 929, in send_error
        self.write_error(status_code, **kwargs)
      File "/home/qiita/american_gut/amgut/handlers/base_handlers.py", line 37, in write_error
        recipient=AMGUT_CONFIG.error_email)
      File "/home/qiita/american_gut/amgut/lib/mail.py", line 52, in send_email
        s.sendmail(sender, [recipient], msg.as_string())
      File "/opt/python-2.7.3/lib/python2.7/smtplib.py", line 733, in sendmail
        raise SMTPRecipientsRefused(senderrs)
    SMTPRecipientsRefused: {"'info@americangut.org'": (501, '5.1.3 Bad recipient address syntax')}
```

**Comment by squirrelo** [comment]
Apparently that __getitem__ error is coming from logging a sample without having a survey attached. Is this supposed to be allowed?

**Comment by wasade** [comment]
No, can you recreate locally?

**Comment by squirrelo** [comment]
I can't recreate this on the main ag site. I'm going to put in a pull request that should catch when this happens and give a more informative error message.

**Comment by wasade** [comment]
My impression is that this is resolved
