### ISSUE TITLE
Odd participant issue

### ISSUE THREAD

**Issue by wasade** [biocore/american-gut-web#347]
Name intentionally replaced below.

```python
[W 141102 09:25:22 web:1404] 404 POST /participants/foo%20bar/ (127.0.0.1): Could not retrieve survey details for participant 'foo bar'
[E 141102 09:25:22 base_handlers:25] (<class 'tornado.web.HTTPError'>, HTTPError(), <traceback object at 0x16e9488>)
    Traceback (most recent call last):
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1332, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 2607, in wrapper
        return method(self, *args, **kwargs)
      File "/home/qiita/american_gut/amgut/handlers/participant_overview.py", line 36, in post
        "participant '%s'" % participant_name)
    HTTPError: HTTP 404: Not Found (Could not retrieve survey details for participant 'foo bar')
```

**Comment by squirrelo** [comment]
There are a few things I'm seeing that relate to either not attaching surveys properly or retrieve them properly. I think something is wrong with ag_data_access.py and surveys. I'll look into it.

**Comment by wasade** [comment]
@squirrelo, I believe this issue has also been resolved, right?

**Comment by squirrelo** [comment]
Yes, this was the registration issues.
