### ISSUE TITLE
Method not allowed

### ISSUE THREAD

**Issue by wasade** [biocore/american-gut-web#353]
[E 141124 19:29:28 base_handlers:31] (<class 'tornado.web.HTTPError'>, HTTPError(), <traceback object at 0x3135998>)
    Traceback (most recent call last):
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1332, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 212, in get
        raise HTTPError(405)
    HTTPError: HTTP 405: Method Not Allowed

**Comment by wasade** [comment]
@squirrelo, we're still receiving these somewhat regularly. Any thoughts?

**Comment by squirrelo** [comment]
If I can get the full traceback I can track down what's up. Can you forward me a few of them?

**Comment by wasade** [comment]
I think the 405s are resolved in the latest pr

**Comment by wasade** [comment]
This is still present, though only a handful of 405s are happening now. Example below

```python
[W 150506 15:10:43 web:1811] 405 POST /AmericanGut/auth/login/ (XXX.XXX.XXX.XXX) 25.92ms
[E 150506 15:10:43 base_handlers:31] (<class 'tornado.web.HTTPError'>, HTTPError(), <traceback object at 0x27f2170>)
    Traceback (most recent call last):
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1332, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 215, in post
        raise HTTPError(405)
    HTTPError: HTTP 405: Method Not Allowed
```

**Comment by wasade** [comment]
Closing as I'm not seeing any of these presently in the logs
