### ISSUE TITLE
500 error on portal

### ISSUE THREAD

**Issue by wasade** [biocore/american-gut-web#381]
```bash
[E 150225 06:27:39 web:1811] 500 GET /authed/portal/ (127.0.0.1) 100.75ms
[E 150225 06:27:39 base_handlers:31] (<type 'exceptions.TypeError'>, TypeError('expected string or buffer',), <traceback object at 0x33fee18>)
    Traceback (most recent call last):
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1332, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 2607, in wrapper
        return method(self, *args, **kwargs)
      File "/home/qiita/american_gut/amgut/handlers/portal.py", line 31, in get
        verification_textbox=verification_textbox)
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 665, in render
        html = self.render_string(template_name, **kwargs)
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 772, in render_string
        return t.generate(**namespace)
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/template.py", line 278, in generate
        return execute()
      File "portal_html.generated.py", line 1062, in _tt_execute
        _tt_tmp = escape(result['participant_name'])  # portal.html:162 (via sitebase.html:166)
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/escape.py", line 69, in xhtml_escape
        to_basestring(value))
    TypeError: expected string or buffer
```

**Comment by wasade** [comment]
This is odd:

```sql
 select akb.barcode, akb.participant_name from ag.ag_kit_barcodes akb inner join ag.ag_kit agk on akb.ag_kit_id=agk.ag_kit_id where akb.participant_name is null and akb.results_ready='Y';
+-----------+------------------+
|  barcode  | participant_name |
+-----------+------------------+
| 000002050 | NULL             |
| 000001000 | NULL             |
| 000001856 | NULL             |
| 000003533 | NULL             |
| 000002165 | NULL             |
| 000002166 | NULL             |
| 000004071 | NULL             |
+-----------+------------------+
(7 rows)
```
