### ISSUE TITLE
Bad GET on sample_overview

### ISSUE THREAD

**Issue by wasade** [biocore/american-gut-web#383]
```bash
[W 150225 11:45:42 web:1811] 400 GET /authed/sample_overview/ (127.0.0.1) 48.85ms
[E 150225 11:45:42 base_handlers:31] (<class 'tornado.web.MissingArgumentError'>, MissingArgumentError(), <traceback object at 0x314d950>)
    Traceback (most recent call last):
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1332, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 2607, in wrapper
        return method(self, *args, **kwargs)
      File "/home/qiita/american_gut/amgut/handlers/sample_overview.py", line 65, in get
        self._sample_overview_renderer()
      File "/home/qiita/american_gut/amgut/handlers/sample_overview.py", line 18, in _sample_overview_renderer
        barcode = self.get_argument('barcode')
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 379, in get_argument
        return self._get_argument(name, default, self.request.arguments, strip)
      File "/opt/python-2.7.3/lib/python2.7/site-packages/tornado-4.0.2-py2.7-linux-x86_64.egg/tornado/web.py", line 448, in _get_argument
        raise MissingArgumentError(name)
    MissingArgumentError: HTTP 400: Bad Request (Missing argument barcode)
```

**Comment by wasade** [comment]
This is just URL hacking. To recreate, just to to `/authed/sample_overview/`
